### ISSUE TITLE
socket_allow_hosts doesn't handle AF_UNIX sockets

### ISSUE THREAD

**Issue by NSchrading** [miketheman/pytest-socket#70] opened 2021-07-22 08:25 UTC
socket_allow_hosts will always block AF_UNIX sockets, even if you pass --allow-unix-socket. The issue is that the code as currently written only handles AF_INET sockets, since host_from_connect_args assumes the args are always tuples, and will return None as the host otherwise.

A simple reproduction can be tested by creating a multiprocessing manager:
```python
manager = multiprocessing.Manager()
lst = manager.list([1, 2, 3])
```

This will raise something like:
```
pytest_socket.SocketConnectBlockedError: A test tried to use socket.socket.connect() with host None (allowed: "foo").
```

socket_allow_hosts should allow any AF_UNIX socket connection if --allow-unix-socket is specified, and it should also work for AF_UNIX sockets with known socket (file) names if you pass the correct name in --allow-hosts.

**Comment by miketheman** [comment] 2021-12-23 19:59
Hello! This should be resolved in #93 - to be released in 0.50.0 soon.

I was unable to reproduce this specific scenario with multiprocessing - please re-test on the new code, and reopen if needed!

**Closed by miketheman** 2021-12-23 19:59 UTC
