### ISSUE TITLE
Unexpected interaction between --disable-socket and --allow-hosts

### ISSUE THREAD

**Issue by sloria** [miketheman/pytest-socket#13] opened 2018-08-03 14:27 UTC
If both `--disable-socket` and `--allow-hosts=somehost` are passed, I would expect all connections to be disabled except for connections to `somehost`. In other words, `allow-hosts` should take precedence.

This isn't currently the case. If both are passed, all connections are disabled.

Thoughts on changing this behavior?

**Comment by sloria** [comment] 2018-08-03 15:34
Alternatively, an error could be raised if both arguments are passed.

I don't have a strong preference for (1) allowing --allow-hosts to take precedence or (2) raise an error. Both are better than the status quo, IMO.

**Comment by miketheman** [comment] 2018-09-06 04:13
I wonder if that has to do with the approach of closest marker, from here:
https://github.com/miketheman/pytest-socket/blob/4c2bd5776775c80b1c2f04d815ac3c004707a1d6/pytest_socket.py#L90

It also looks like there's not the test case you're specifying - but I feel like the `--allow-hosts` ought to disable anything other than the allowed hosts, so adding the `--disable-socket` would be unnecessary.

**Comment by sloria** [comment] 2018-09-06 13:13
> adding the --disable-socket would be unnecessary.

True, but it's un-intuitive for `--disable-socket` to take precedence over `--allow-hosts` when both are passed. Either allow users to pass both and fix the behavior or disallow passing both (i.e. raise an error).

**Comment by SHxKM** [comment] 2019-08-03 22:45
@sloria - did you find an elegant way to deal with?

**Comment by atugushev** [comment] 2019-11-02 14:49
I believe this is because `disable_socket` resets the guard set by `socket_allow_hosts`, see: https://github.com/miketheman/pytest-socket/blob/262513b83e785687a062c4eb2d564355c67e4930/pytest_socket.py#L68-L75

**Comment by miketheman** [comment] 2020-05-31 15:18
Version 0.3.5 was just released with a slight modification to the ordering behavior of `disable-socket` and how it might impact the `allow-hosts` approach.

Can someone who's been impacted by this re-test, and if it's still not working, provide reproducible example? Some good guidance here: https://stackoverflow.com/help/minimal-reproducible-example

**Comment by joetsoi** [comment] 2021-03-05 14:26
https://github.com/urllib3/urllib3/blob/main/src/urllib3/util/connection.py#L63-L72

So I've bumped into this due to the way socket is used in urllib3, `socket.socket` is called before `socket.socket.connect`. Causing a `SocketBlockedError()` to be raised before the guarded `connect` is called.

Current behaviour `disable_socket` does _not_ reset the guard, but it just blocks at an earlier point.

Why would I want to  do this? Because I want to `--disable-socket` and then allow hosts for a specific test, so best way to allow that is to mark with both `allowed_hosts` and `enable_socket`

```
        @pytest.mark.allowed_hosts("localhost")
        @pytest.mark.enable_socket
        def test_something():
            ...
```

It sounds like erroring when both `--allowed-hosts` and `--disable-socket` might be sensible, and maybe add something to the docs with the above example if you want to enable for specific tests?

**Comment by ryanjdillon** [comment] 2021-09-17 13:57
I just ran into this, as I'm using motoserver to mock AWS services, so I want to allow connections to localhost, and block to AWS. 

I also assumed that `--disable-socket --allow-hosts=127.0.01,localhost` would do what I wanted. I only discovered this behavior by looking through the issues here.

**Comment by miketheman** [comment] 2021-11-12 00:30
Thanks for the input everyone - I think I have enough details to establish what's wrong.

TL,DR: there's a logical conflict between the config options, leading to failed outcomes. This is likely to change the
flag combinations, so I'm treading carefully.

**Comment by miketheman** [comment] 2021-12-22 20:40
Hey gang! Thanks for your patience - I've worked out the precedence levels, and have pushed the latest code the the `main` branch. I'll aim to cut a release sometime within the next couple of weeks, keep an eye out for that!

**Closed by miketheman** 2021-12-22 20:40 UTC
Labels: bug
