### ISSUE TITLE
plugin broken by pytest 4.1

### ISSUE THREAD

**Issue by wimglenn** [miketheman/pytest-socket#19] opened 2019-01-07 22:41 UTC
```
    @pytest.fixture(autouse=True)
    def _socket_marker(request):
>       if request.node.get_marker('disable_socket'):
E       AttributeError: 'TestCaseFunction' object has no attribute 'get_marker'

```

**Comment by wimglenn** [comment] 2019-01-07 22:42
Related pytest PR https://github.com/pytest-dev/pytest/issues/4546

**Comment by miketheman** [comment] 2019-01-07 22:49
Duplicate of #16

**Closed by miketheman** 2019-01-07 22:49 UTC

**Comment by wimglenn** [comment] 2019-01-07 22:50
Exactly. Apologies, I should have checked in master.
